### ISSUE TITLE
无法获取原有数据

### ISSUE THREAD

**Issue by rockmelodies** [Weeken/vue-wangeditor-simple#10]
获取文章内容 无法再编辑器显示

**Comment by Weeken** [comment]
@rockmelodies 能详细说明吗？具体怎么复现？

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/41031538-782266b6-69b3-11e8-9d88-6aed2943ded4.png)
首先先从前端提交数据
![image](https://user-images.githubusercontent.com/24653177/41031737-0b4670a4-69b4-11e8-804a-02ce910a4417.png)
![image](https://user-images.githubusercontent.com/24653177/41031781-2be56220-69b4-11e8-842b-4088fe1de5a3.png)
后端审核无法获取数据
后端走的api
![image](https://user-images.githubusercontent.com/24653177/41031831-4c4d311e-69b4-11e8-87f1-69bd520b13ea.png)
![image](https://user-images.githubusercontent.com/24653177/41031844-5365c380-69b4-11e8-9457-9efa7bf3e33b.png)
![image](https://user-images.githubusercontent.com/24653177/41031855-591dc1c4-69b4-11e8-9c94-7ac64606ed53.png)
![image](https://user-images.githubusercontent.com/24653177/41031862-60459e7c-69b4-11e8-869e-cfcc63aed3ce.png)
![image](https://user-images.githubusercontent.com/24653177/41031872-662e80b0-69b4-11e8-9594-3a8a7896e5d4.png)

**Comment by rockmelodies** [comment]
后端 引用vue 无法显示 数据库已经有的 html

**Comment by rockmelodies** [comment]
我要做个 编辑 审核功能

**Comment by Weeken** [comment]
这个有个init-content的prop可以初始化内容，因为之前也是用v-model传入的，但这样输入的时候会有影响，所以我就把这个分开了。
你用这个prop传进入就会同步到v-model了

发自我的 iPhone

在 2018年6月6日，下午6:48，rockymelody <notifications@github.com<mailto:notifications@github.com>> 写道：


我要做个 编辑 审核功能

**Comment by Weeken** [comment]
@rockmelodies 我最新的代码版本是1.5.55

**Comment by Weeken** [comment]
@rockmelodies 看看我的readme.md就知道了

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/41071302-8bd50026-6a29-11e8-9e99-ff9328c579ff.png)
还是不行
这是mysql 存入大格式
![image](https://user-images.githubusercontent.com/24653177/41071319-a3f6bb54-6a29-11e8-8be8-b323ec783c0a.png)
![image](https://user-images.githubusercontent.com/24653177/41071339-c064de9c-6a29-11e8-9d31-fa9f1cb4befc.png)

**Comment by Weeken** [comment]
你写错了，是:init-content=“details”

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/41071491-94983d4e-6a2a-11e8-8a48-b3599e49fe76.png)

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/41071513-b1ce6578-6a2a-11e8-87da-0fc9d5d1033a.png)

**Comment by Weeken** [comment]
更新了版本没有？1.5.55

**Comment by Weeken** [comment]
这样还是不行吗？

**Comment by rockmelodies** [comment]
可以了，非常感谢

**Comment by Weeken** [comment]
好的，还有问题就再来吧

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/41071591-520c7fde-6a2b-11e8-8d3c-bdaf3d2fef76.png)
改成这样可以了
![image](https://user-images.githubusercontent.com/24653177/41071607-69cd56b6-6a2b-11e8-9583-0e432454bc10.png)

**Comment by Weeken** [comment]
看截图是不是编辑器里嵌着一个编辑器了？

**Comment by rockmelodies** [comment]
不是，里面是我的截图
