### ISSUE TITLE
如何在浏览器中直接使用通过script 引入的方式情况下

### ISSUE THREAD

**Issue by PDieE** [Weeken/vue-wangeditor-simple#11]
如何在浏览器中直接使用通过script 引入的方式情况下

**Comment by Weeken** [comment]
@hxywuya 想这样引入的话，你就别用我这个了，直接引入wangeditor就行了

**Comment by PDieE** [comment]
遇到个坑按官网示例用报 初始化编辑器时候未传入任何参数，请查阅文档  错误
然后我改成用ID获取会报 The given range isn't in document. 错误····

**Comment by Weeken** [comment]
@hxywuya 能看看代码吗？
