### ISSUE TITLE
多个编辑框距离过近时，改变颜色的菜单会显示出下一个编辑框的内容

### ISSUE THREAD

**Issue by Mu-xue** [Weeken/vue-wangeditor-simple#14]
错误重现：
![image](https://user-images.githubusercontent.com/26177732/54911239-fdfccc80-4f28-11e9-9312-d510a6c14bbe.png)

**Comment by Weeken** [comment]
![image](https://user-images.githubusercontent.com/18238515/55138360-33dec280-516e-11e9-8e0c-f80d39233c89.png)
