### ISSUE TITLE
发现v-model和init-content同时使用相同的变量值，输入内容会自动换行

### ISSUE THREAD

**Issue by zhujinhu21** [Weeken/vue-wangeditor-simple#16]
v-model和init-content一起使用相同的模型变量的值，v-model="form.analysis" :init-content="form.analysis"（修改编辑的时候我需要先赋值初始化），在输入内容会自动换行

**Comment by Weeken** [comment]
可以的话分开两个字段吧，之前就是发现用同一个字段的时候输入会有问题，所以才分开两个字段的
