### ISSUE TITLE
配置后不显示上传图片选项

### ISSUE THREAD

**Issue by zhujinhu21** [Weeken/vue-wangeditor-simple#18]
// 下面两个配置，使用其中一个即可显示“上传图片”的tab。但是两者不要同时使用！！！
    // editor.customConfig.uploadImgShowBase64 = true   // 使用 base64 保存图片
    // editor.customConfig.uploadImgServer = '/upload'  // 上传图片到服务器

配置后，不显示上传图片选项

**Comment by Weeken** [comment]
> ```
> // 下面两个配置，使用其中一个即可显示“上传图片”的tab。但是两者不要同时使用！！！
> // editor.customConfig.uploadImgShowBase64 = true   // 使用 base64 保存图片
> // editor.customConfig.uploadImgServer = '/upload'  // 上传图片到服务器
> ```
> 
> 配置后，不显示上传图片选项

```
<vue-wangeditor id="editor" :options="editorOptions" v-model="content" :text.sync="text" :init-content="initContent" :disabled="false"></vue-wangeditor>
```
------
```
editorOptions: {
        width: '850px',
        height: '50px',
        menus: [
          'image',  // 插入图片
          'head',  // 标题
          'bold',  // 粗体
          'italic',  // 斜体
          'underline',  // 下划线
          'strikeThrough',  // 删除线
          'foreColor',  // 文字颜色
          'backColor',  // 背景颜色
          'link',  // 插入链接
          'list',  // 列表
          'justify',  // 对齐方式
          'quote',  // 引用
          // 'emoticon',  // 表情
          'table',  // 表格
          // 'video',  // 插入视频
          'code',  // 插入代码
          'undo',  // 撤销
          'redo',  // 重复
          'clearStyle', //清除文字的样式
          'clearFormat', //清除文字的格式
          'clearAll', //一键清空编辑器
          'insertCode',
          'fullscreen' // 全屏
        ],
        pasteFilterStyle: false,  // 关闭粘贴样式的过滤
        // uploadImgShowBase64: true,
        uploadImgServer: 'https://up-z2.qbox.me/',
        uploadFileName: 'file',
        uploadImgMaxLength: 1,
        uploadImgParams: {
          token: ''   // 属性值会自动进行 encode ，此处无需 encode
        }
```
![image](https://user-images.githubusercontent.com/18238515/92546461-2e533a80-f285-11ea-8b4b-1b2c8ad499a3.png)
我的是有的，看看有没有配置错了 @zhujinhu21

**Comment by Weeken** [comment]
![image](https://user-images.githubusercontent.com/18238515/92547091-af5f0180-f286-11ea-9e4c-032646272d00.png)
必须在```editor.create()```之前就配置好，否则不生效。由于我的组件内部会调用此方法，所以配置项必须写在editorOptions里面。看看你是不是这个问题？@zhujinhu21

**Comment by zhujinhu21** [comment]
解决了，谢谢
