### ISSUE TITLE
v-model 把文字都删除后，文本框没有清空

### ISSUE THREAD

**Issue by marx828** [Weeken/vue-wangeditor-simple#2]
v-model绑定值后，把文本框中文字都删除后，v-model的值没有清空，而是变成<p><br></p>

**Comment by Weeken** [comment]
这个是编辑器自动生成的html标签，不影响你输入内容，你可以把这些用v-html来显示

**Comment by marx828** [comment]
但是我想做非空校验时候，怎么办呢。。

**Comment by Weeken** [comment]
你可以把“\<p/>\<br\>\</p\>"当作是空

**Comment by marx828** [comment]
我现在想获取文本框中的text，怎么获取嘞？就是我新提出的那个问题。。希望大神指导啊~

**Comment by Weeken** [comment]
v-model不是绑定了吗？

**Comment by marx828** [comment]
是，但是他要是很多回车的话就不只是“<-p/><-br></p->"这个代码了，就会是很多个'<-p>'和'<-br>'，就只能是需要获取到文本框的text才能指导到底有没有录入东西

**Comment by Weeken** [comment]
这个我要改改，或者你用个方法把里面的标签都去掉

**Comment by marx828** [comment]
哦哦，这个没法用官网的方法获取了是嘛？

**Comment by Weeken** [comment]
暂时不行，因为之前没这个需求
