### ISSUE TITLE
怎么获取文本框的内容呢？

### ISSUE THREAD

**Issue by marx828** [Weeken/vue-wangeditor-simple#3]
我看官网是editor.txt.text()这样获取的，用咱们这个控件是怎么获取的？

**Comment by marx828** [comment]
我这个就是想做校验，但是没办法取到文本框的内容，急急急！！！

**Comment by Weeken** [comment]
你想怎么取？取哪部分的内容？包括HTML标签吗？可以贴贴代码看看吗？

**Comment by marx828** [comment]
就是只取文本框中的text，不包含html。我看wangeditor的官网文档中是支持获取的，他是这么获取的：

var E = window.wangEditor
    var editor = new E('#div1')
    editor.create()

    document.getElementById('btn1').addEventListener('click', function () {
        // 读取 html
        alert(editor.txt.html())
    }, false)

    document.getElementById('btn2').addEventListener('click', function () {
        // 读取 text
        alert(editor.txt.text())
    }, false)

**Comment by Weeken** [comment]
好了，你下载最新的包吧，已经添加了这个功能

**Comment by Weeken** [comment]
已经更新包了，你下载最新的包吧

发自我的 iPhone

在 2017年10月18日，下午4:35，marx828 <notifications@github.com<mailto:notifications@github.com>> 写道：


就是只取文本框中的text，不包含html。我看wangeditor的官网文档中是支持获取的，他是这么获取的：

var E = window.wangEditor
var editor = new E('#div1')
editor.create()

document.getElementById('btn1').addEventListener('click', function () {
    // 读取 html
    alert(editor.txt.html())
}, false)

document.getElementById('btn2').addEventListener('click', function () {
    // 读取 text
    alert(editor.txt.text())
}, false)

**Comment by marx828** [comment]
好的，非常感谢
