### ISSUE TITLE
清楚当前格式的工具栏

### ISSUE THREAD

**Issue by marx828** [Weeken/vue-wangeditor-simple#4]
大神，现在有个清楚文本当前格式的需求，能不能加上呀，我看目前菜单栏，没有这个功能

**Comment by Weeken** [comment]
这个你应该找编辑器的作者，我只是把编辑器做成Vue插件而已。
你可以配置 ”关闭粘贴样式的过滤“ 来过滤掉样式，这样相当于粘贴纯文本了。
![image](https://user-images.githubusercontent.com/18238515/32152405-dd929022-bd5e-11e7-9208-737d3ddabe10.png)

**Comment by Weeken** [comment]
最新版本菜单栏有了清除格式功能---clearFormat，清除样式---clearStyle，你试试看
