### ISSUE TITLE
把富文本框中文字，用鼠标全选后，然后按键盘delete删除后，文本框清空，但是model值无法清空

### ISSUE THREAD

**Issue by marx828** [Weeken/vue-wangeditor-simple#5]
把富文本框中文字，用鼠标全选后，然后按键盘delete删除后，文本框清空，但是model值无法清空？楼主有发现这问题不？

**Comment by Weeken** [comment]
![image](https://user-images.githubusercontent.com/18238515/32267009-aed67100-bf24-11e7-8d3e-392d1238dc33.png)
如果content的值是这样，那就没问题啊，text的值已经清空了

**Comment by marx828** [comment]
我这用我说的方式，为什么会出现没清空的方式呢。。还有别的方式获取到富文本中的内容不？

**Comment by Weeken** [comment]
能截个图看看怎样没清空吗？text的值不就是你的内容吗？

**Comment by marx828** [comment]
我这只能是console他的model值，你这个截图是怎么看的呢？

**Comment by Weeken** [comment]
你去下载一个vue的开发者工具Chrome插件

![wx20171101-175340](https://user-images.githubusercontent.com/18238515/32269565-bae6941c-bf2d-11e7-8cf8-00093cc97ce5.png)
