### ISSUE TITLE
Error in mounted hook: "TypeError: Cannot read property 'includes' of undefined"

### ISSUE THREAD

**Issue by xsdhy** [Weeken/vue-wangeditor-simple#6]
`vue.esm.js?5425:578 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'includes' of undefined"

found in

---> <VueWangeditor>
       <Card>
         <ICol>
           <Row>
             <ArticleEdit> at src/components/article-edit.vue
               <Layout>
                 <App> at src/App.vue
                   <Root>
warn @ vue.esm.js?5425:578
logError @ vue.esm.js?5425:1713
globalHandleError @ vue.esm.js?5425:1708
handleError @ vue.esm.js?5425:1697
callHook @ vue.esm.js?5425:2897
insert @ vue.esm.js?5425:4090
invokeInsertHook @ vue.esm.js?5425:5864
patch @ vue.esm.js?5425:6083
Vue._update @ vue.esm.js?5425:2637
updateComponent @ vue.esm.js?5425:2765
get @ vue.esm.js?5425:3115
Watcher @ vue.esm.js?5425:3104
mountComponent @ vue.esm.js?5425:2772
Vue$3.$mount @ vue.esm.js?5425:8429
Vue$3.$mount @ vue.esm.js?5425:10790
Vue._init @ vue.esm.js?5425:4570
Vue$3 @ vue.esm.js?5425:4659
(anonymous) @ main.js?1c90:35
./src/main.js @ app.js:2003
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:2020
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
vue.esm.js?5425:1717 TypeError: Cannot read property 'includes' of undefined
    at VueComponent.mounted (vue-wangeditor-simple.js?075c:1)
    at callHook (vue.esm.js?5425:2895)
    at Object.insert (vue.esm.js?5425:4090)
    at invokeInsertHook (vue.esm.js?5425:5864)
    at Vue$3.patch [as __patch__] (vue.esm.js?5425:6083)
    at Vue$3.Vue._update (vue.esm.js?5425:2637)
    at Vue$3.updateComponent (vue.esm.js?5425:2765)
    at Watcher.get (vue.esm.js?5425:3115)
    at new Watcher (vue.esm.js?5425:3104)
    at mountComponent (vue.esm.js?5425:2772)`

**Comment by Weeken** [comment]
让我看看你传进去给编辑器的配置代码

**Comment by Weeken** [comment]
应该可以了，你重新安装一下
