### ISSUE TITLE
编辑器后面4个功能字体图标在部分浏览器中不兼容

### ISSUE THREAD

**Issue by liuguanhua** [Weeken/vue-wangeditor-simple#8]
## 编辑器后面增加的四个功能中字体图标在微信打开浏览器中和360浏览器中字体图标不显示。
![image](https://user-images.githubusercontent.com/15644158/38719143-ff005b22-3f22-11e8-90e5-794c90151e37.png)
![image](https://user-images.githubusercontent.com/15644158/38719155-0f0a15e4-3f23-11e8-8ba7-dbe3e2b26059.png)

**Comment by Weeken** [comment]
@liuguanhua 请问浏览器的版本

**Comment by Weeken** [comment]
@liuguanhua 
![image](https://user-images.githubusercontent.com/18238515/38721240-e99e7c92-3f2b-11e8-81d6-b97587d71e93.png)
![image](https://user-images.githubusercontent.com/18238515/38721244-ee8b3754-3f2b-11e8-9a08-1e34634fca83.png)

**Comment by liuguanhua** [comment]
@Weeken 
一个360极速浏览器9.5，还有就是微信客户端聊天时发送聊天信息打开链接自带的浏览器，具体版本看不了。
![image](https://user-images.githubusercontent.com/15644158/38721298-33c48eba-3f2c-11e8-8b48-55eed73d39c5.png)

**Comment by Weeken** [comment]
@liuguanhua 
![image](https://user-images.githubusercontent.com/18238515/38722078-592d6ef8-3f2f-11e8-95e6-a793f1ecfb54.png)
![image](https://user-images.githubusercontent.com/18238515/38722089-5e913334-3f2f-11e8-8221-63a92fa8a54a.png)
![image](https://user-images.githubusercontent.com/18238515/38722095-61ecefe6-3f2f-11e8-8e4f-64651b4cd3bb.png)

**Comment by Weeken** [comment]
@liuguanhua 看看插件是否是最新版--1.5.54

**Comment by liuguanhua** [comment]
@Weeken 是1.5.54，这是我安装的npm包信息
![image](https://user-images.githubusercontent.com/15644158/38723158-cd08daf8-3f32-11e8-934d-f3fc59d745ae.png)

**Comment by Weeken** [comment]
@liuguanhua 这几个按钮必须在menus里面配置的
`menus: [
    ...
  'clearStyle', //清除文字的样式
   'clearFormat', //清除文字的格式
   'clearAll', //一键清空编辑器
  'insertCode',
   'fullscreen' // 全屏
]`

**Comment by liuguanhua** [comment]
@Weeken 那个也配置了，你打包出来的生成环境也是可以的吗？开发环境好像是没问题
![image](https://user-images.githubusercontent.com/15644158/38724293-5a443f86-3f36-11e8-86ec-a5c1fd8b44f2.png)

**Comment by Weeken** [comment]
@liuguanhua  可以的
![image](https://user-images.githubusercontent.com/18238515/38725937-622d3cd4-3f3b-11e8-9140-e75e1eaec7af.png)
这个是我的个人博客上的

**Comment by Weeken** [comment]
@liuguanhua 方便看代码吗？看你的图感觉是插件里的代码没执行到

**Comment by Weeken** [comment]
@liuguanhua 先看看菜单里是不是没有生成元素

**Comment by liuguanhua** [comment]
@Weeken 我把360浏览器开成极速模式就没问题了，或者你看一下你把360浏览器开成兼容模式会不会有。

**Comment by Weeken** [comment]
@liuguanhua 
兼容模式：ie9
![_20180413173844](https://user-images.githubusercontent.com/18238515/38728216-cda3624e-3f41-11e8-880a-ae9160cd4774.png)
兼容模式：ie10
![_20180413173951](https://user-images.githubusercontent.com/18238515/38728222-d5e86dfa-3f41-11e8-9a69-b5145f8322b1.png)

**Comment by Weeken** [comment]
@liuguanhua 线上的 https://admin.weeken.top/#/addNote

**Comment by liuguanhua** [comment]
@Weeken 你发的这个链接我用360浏览器兼容模式访问了的确是没问题，我先把代码分离出来看会不会出现问题，谢谢你

**Comment by liuguanhua** [comment]
@Weeken 找到原因了，在兼容模式下报对象不支持“includes”属性或方法，在项目中我也没使用includes方法，我看在vue-wangeditor-simple插件包clearFormat.js中有使用includes方法。
![image](https://user-images.githubusercontent.com/15644158/38764894-27630a98-3fea-11e8-9ebb-46559d920da6.png)
![image](https://user-images.githubusercontent.com/15644158/38764755-6fbaa1aa-3fe7-11e8-8a9f-4592e355fe2f.png)
![image](https://user-images.githubusercontent.com/15644158/38764903-716c13f0-3fea-11e8-87f5-f8faf9295c75.png)
我添加了babel-polyfill包就好像没问题了
![image](https://user-images.githubusercontent.com/15644158/38764872-b9bdfa48-3fe9-11e8-9d3d-92547467e6a4.png)
![image](https://user-images.githubusercontent.com/15644158/38764878-d1e4d1be-3fe9-11e8-8fac-9c0df3a43f7d.png)

**Comment by Weeken** [comment]
@liuguanhua 不应该第一时间就去看有没有报错的吗？。。。

**Comment by liuguanhua** [comment]
@Weeken 是开始用微信浏览器客户端访问没有显示，查看控制台，然而微信浏览器没提供，我以为是字体兼容的问题，后面用360访问，右键我也没有看到有审查元素，后面才查看到360浏览器设置那里有个开发者工具，才知晓的，谢谢你，是我的问题。

**Comment by Weeken** [comment]
@liuguanhua  不客气，解决了就好了。还有360，IE等浏览器按个F12就可以打开开发者工具了。还有问题的话，欢迎继续。。

**Comment by liuguanhua** [comment]
@Weeken 👍，是一直解决问题的方向，思路不对，没用Windows电脑开发，就不常按F12了

**Comment by liuguanhua** [comment]
@Weeken 👍，是一直解决问题的方向，思路不对。
