### ISSUE TITLE
没有本地上传图片

### ISSUE THREAD

**Issue by zhilizhui** [Weeken/vue-wangeditor-simple#9]
本地上传图片怎么设置呢

**Comment by Weeken** [comment]
@zhilizhui [可以参考这里](https://www.kancloud.cn/wangfupeng/wangeditor3/335782)
如果上传七牛云的，也可以这样设置，不必按官网的
`uploadImgServer: 'https://up-z2.qbox.me/',
        uploadFileName: 'file',
        uploadImgMaxLength: 1,
        uploadImgParams: {
          token: '' // 属性值会自动进行 encode ，此处无需 encode
        },
        uploadImgParamsWithUrl: true,
        uploadImgHooks: {
          // success: (xhr, editor, result) => {
          //   // 图片上传并返回结果，图片插入成功之后触发
          //   // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象，result 是服务器端返回的结果
          //   // console.log(result)
          // },
          // fail: (xhr, editor, result) => {
          //   // console.log(result)
          // },
          customInsert: (insertImg, result/*, editor*/) => {
            // console.log(insertImg)
            let url = `http://p0ry9w0d5.bkt.clouddn.com/${result.key}`
            insertImg(url)
          }
        }`

**Comment by zhujinhu21** [comment]
怎么显示上传图片选项 设置了editor.customConfig.uploadImgServer = '/upload'

**Comment by zhujinhu21** [comment]
@zhilizhui 请问你是怎么解决的？vue-wangeditor-simple create之后设置editor.customConfig.uploadImgServer = '/upload' 无效
